apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: divyafinal-deploy
  name: divyafinal-deploy
  namespace: divya-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: divyafinal-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: divyafinal-deploy
    spec:
      containers:
      - image: divyahcl/divyahcl:appfinal
        name: divyahcl
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: divyafinal-deploy
  name: divyalb1088
  namespace: divya-project
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: divyafinal-deploy
  type: NodePort
status:
  loadBalancer: {}
